# Generated by Django 5.1.5 on 2025-01-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('landlord_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo')], default='house', max_length=10)),
                ('pets_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('ada_accessible', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('income_requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('past_eviction_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('sex_offender_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('criminal_record_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('issues_allowed', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
