# Generated by Django 4.1.5 on 2025-02-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0003_alter_listing_income_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='income_requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
