# Generated by Django 4.1.5 on 2025-03-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0004_alter_listing_income_requirement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='additional_info',
            new_name='misc_notes',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='landlord_contact',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='landlord_cell',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='landlord_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='criminal_record_allowed',
            field=models.CharField(choices=[('none', 'None Allowed (Clear Record Only)'), ('misdemeanor', 'Misdemeanor Allowed (Per Review)'), ('felony', 'Felony Allowed (Per Review)')], default='none', max_length=12),
        ),
        migrations.AlterField(
            model_name='listing',
            name='income_requirement',
            field=models.CharField(blank=True, choices=[('under_20', 'Under $20,000'), ('30_40', '$30,000-$40,000'), ('40_50', '$40,000-$50,000'), ('50_plus', '$50,000 and Above')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('group_home', 'Group Home')], default='house', max_length=20),
        ),
    ]
