# Generated by Django 4.1.5 on 2025-03-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_app', '0005_rename_image_listing_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='issues_allowed',
        ),
        migrations.AddField(
            model_name='listing',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
