# Generated by Django 4.1.5 on 2025-06-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing_app", "0011_rename_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="two_factor_secret",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
